import Image from "next/image";
import type { Metadata } from "next";
import { ButtonLink, Container, Eyebrow } from "@/components/ui";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "IB Mathematics IA book by Robert Flynn", description: "IB Mathematics IA: The Complete Guide to the Internal Assessment by Robert Flynn. A 320-page practical guide for IB Mathematics students." };

export default function BookPage() {
  return (
    <>
      <section className="book-page-hero"><Container className="book-page-grid"><div className="book-page-cover"><Image src="/images/ib-mathematics-ia-book-cover.jpg" alt="Cover of IB Mathematics IA: The Complete Guide to the Internal Assessment by Robert Flynn" width={577} height={816} priority /><span>Published 2025</span></div><div className="stack-lg"><Eyebrow>The book by Robert Flynn</Eyebrow><h1>IB Mathematics IA</h1><h2>The Complete Guide to the Internal Assessment</h2><p className="lede">A practical guide that breaks the Maths IA into clear, manageable stages—showing you what examiners are looking for and how to communicate your mathematics with confidence.</p><div className="book-meta"><span><strong>320</strong> pages</span><span><strong>Paperback</strong> format</span><span><strong>9781068444234</strong> ISBN</span></div><div className="cluster"><ButtonLink href={siteConfig.bookUrl} external>View on Amazon</ButtonLink><ButtonLink href="/ia" secondary>Watch the free IA guides</ButtonLink></div></div></Container></section>
      <section className="section book-benefits"><Container className="stack-xl"><div className="section-heading-row"><div className="stack"><Eyebrow>Inside the guide</Eyebrow><h2>A route through the whole process.</h2></div><p className="lede">Use it from the earliest idea through to the final submission, with guidance grounded in Rob&apos;s experience as a teacher, examiner and moderator.</p></div><div className="grid-3"><article><span>01</span><h3>Make the task manageable</h3><p>Break a large, intimidating assessment into decisions you can handle one at a time.</p></article><article><span>02</span><h3>See what examiners need</h3><p>Understand the purpose of the criteria and what strong mathematical communication looks like.</p></article><article><span>03</span><h3>Learn through examples</h3><p>Use clear strategies and real mathematical examples to develop your own exploration.</p></article></div></Container></section>
      <section className="book-author-section"><Container className="book-author-grid"><div className="book-author-photo"><Image src="/images/rob-flynn.webp" alt="Robert Flynn, author of IB Mathematics IA" fill sizes="(max-width: 800px) 100vw, 42vw" /></div><div className="stack-lg"><Eyebrow>About the author</Eyebrow><h2>Written by the teacher behind Mr Flynn IB.</h2><p className="lede">Robert Flynn is an IB Mathematics teacher, examiner and moderator whose video lessons and IA guidance have reached students around the world.</p><p>The book brings that same clear, direct teaching style into a reference students can use throughout their Internal Assessment.</p><ButtonLink href="/about" secondary>More about Rob</ButtonLink></div></Container></section>
    </>
  );
}
