import type { Metadata } from "next";
import { EnquiryForm } from "@/components/enquiry-form";
import { Container, Eyebrow, PageHero, PlaceholderNote } from "@/components/ui";

export const metadata: Metadata = { title: "Private IB Mathematics tutoring", description: "Apply for selective, expert-led IB Mathematics tutoring with Mr Flynn IB." };

export default function TutoringPage() {
  return <>
    <PageHero eyebrow="Private tutoring" title="Focused support when a course alone is not enough." intro="A selective tutoring service for IB Mathematics students who need diagnosis, direct feedback and a clear plan—not simply another hour of generic homework help." />
    <section className="section-tight"><Container className="grid-3"><article className="card stack"><span className="icon-box">◎</span><h3>Diagnose the real gap</h3><p className="muted">Separate missing knowledge from weak algebra, calculator habits, exam judgement or confidence.</p></article><article className="card stack"><span className="icon-box">↻</span><h3>Build a repeatable method</h3><p className="muted">Turn each session into a plan the student can apply independently between lessons.</p></article><article className="card stack"><span className="icon-box">✓</span><h3>Use honest feedback</h3><p className="muted">Focus on the exact changes most likely to improve performance rather than covering content for its own sake.</p></article></Container></section>
    <section className="section surface"><Container className="split"><div className="stack-lg"><Eyebrow>Who tutoring is for</Eyebrow><h2>Best suited to students ready to engage seriously.</h2><ul className="check-list"><li>Students with persistent gaps that videos alone have not resolved</li><li>Students preparing for a high-stakes exam session</li><li>Students who need accountability and a structured weekly plan</li><li>Families looking for specialist IB Mathematics support</li></ul><PlaceholderNote>Confirm whether Rob teaches every session personally, whether approved tutors may deliver sessions, available time zones, session length, pricing and minimum commitment.</PlaceholderNote></div><div className="card stack-lg"><h3>How the process works</h3><ol className="stack" style={{ paddingLeft: "1.25rem" }}><li><strong>Apply.</strong> Tell us about the student, course, target and current difficulty.</li><li><strong>Assess fit.</strong> We review whether tutoring is the right intervention and whether suitable availability exists.</li><li><strong>Agree a plan.</strong> The first session identifies priorities and sets expectations.</li><li><strong>Review progress.</strong> Lessons should produce visible independent improvement, not dependency.</li></ol></div></Container></section>
    <section className="section"><Container className="split"><div className="stack-lg"><Eyebrow>Apply for tutoring</Eyebrow><h2>Tell us what the student needs.</h2><p className="lede">The application gathers enough context to make the first response useful. It does not guarantee availability.</p></div><EnquiryForm kind="tutoring" /></Container></section>
  </>;
}
