import type { Metadata } from "next";
import { EnquiryForm } from "@/components/enquiry-form";
import { Container, Eyebrow, PageHero, PlaceholderNote } from "@/components/ui";

export const metadata: Metadata = { title: "IB Mathematics school licences", description: "Structured Mr Flynn IB course access for schools, departments and student cohorts." };

export default function SchoolsPage() {
  return <>
    <PageHero eyebrow="For schools" title="Expert IB Mathematics support across the department." intro="Give students clear, on-demand explanations while giving teachers a consistent resource they can recommend with confidence." />
    <section className="section-tight"><Container className="grid-3"><article className="card stack"><span className="icon-box">⌁</span><h3>Consistent student access</h3><p className="muted">A shared bank of structured explanations students can use in class, at home and during revision.</p></article><article className="card stack"><span className="icon-box">⏱</span><h3>Save teacher time</h3><p className="muted">Reduce repeated reteaching and give absent or struggling students a dependable next step.</p></article><article className="card stack"><span className="icon-box">◫</span><h3>Simple procurement</h3><p className="muted">A school-friendly enquiry, quotation and invoice route rather than individual consumer purchases.</p></article></Container></section>
    <section className="section surface-ink"><Container className="split"><div className="stack-lg"><Eyebrow>What a licence can include</Eyebrow><h2>Built for departments, not just bulk checkout.</h2><p className="lede">The offer should combine student access with onboarding and a clear institutional relationship.</p></div><div className="grid-2"><div className="number-card"><strong>01</strong><h3>Course access</h3><p>Selected AA and AI courses for the agreed cohort.</p></div><div className="number-card"><strong>02</strong><h3>Onboarding</h3><p>A clear setup route for staff and students.</p></div><div className="number-card"><strong>03</strong><h3>Teacher support</h3><p>Guidance on where the resources fit best.</p></div><div className="number-card"><strong>04</strong><h3>Renewal plan</h3><p>Simple annual review and continuation.</p></div></div></Container></section>
    <section className="section surface"><Container className="stack-xl"><div className="stack"><Eyebrow>Proposed licence structure</Eyebrow><h2>Three starting points for commercial design.</h2><p className="lede">These are deliberately presented as a framework until the actual Teachable licensing mechanics and pricing are confirmed.</p></div><div className="grid-3"><article className="card stack-lg"><span className="badge">Small cohort</span><h3>Up to 25 students</h3><p className="muted">Suitable for one class or a targeted intervention group.</p></article><article className="card stack-lg"><span className="badge">Department</span><h3>Up to 100 students</h3><p className="muted">Suitable for several classes across pathways or year groups.</p></article><article className="card stack-lg"><span className="badge">Custom</span><h3>Multi-cohort access</h3><p className="muted">For larger schools, groups or tailored implementation.</p></article></div><PlaceholderNote>Set licence duration, prices, named-user rules, transfer policy, usage reporting, teacher accounts, onboarding, renewal and Teachable bulk-enrolment process. Preserve Mr Flynn IB’s IP, brand ownership and customer relationship in any partner arrangement.</PlaceholderNote></Container></section>
    <section className="section"><Container className="split"><div className="stack-lg"><Eyebrow>Request school information</Eyebrow><h2>Start with your cohort and priorities.</h2><p className="lede">We can then respond with the most relevant access model, demonstration and quotation route.</p></div><EnquiryForm kind="school" /></Container></section>
  </>;
}
